apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-deployment
  labels:
    app: node-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          imagePullPolicy: Always
          image: arthurescriou/node-redis:1.0.5
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: 8080
            - name: REDIS_URL
              value: redis://redis:6379
